# Exclude virtual environment from all hooks
exclude: ^venv/

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: []

  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.3.2
    hooks:
      - id: docstr-coverage
        args: ["--config=.docstr.yaml", "--accept-empty", "src/beer"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONDONTWRITEBYTECODE=1 pytest -q --cache-clear && rm -f replay_pkt.bin'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
