services:
  server:
    build: .
    container_name: beer-server
    command: python -m beer.server
    environment:
      - BEER_PORT=5000
      - BEER_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"

  client:
    build: .
    depends_on:
      - server
    command: python -m beer.client --host server --port 5000
    stdin_open: true  # keep STDIN open for interactive input
    tty: true         # allocate a pseudo-TTY for nicer prompts
    # Scale additional clients at runtime via: `docker-compose up --scale client=3`
